networks:
  dev:

services:
  nginx:
    ports:
      - "8097:8097"
    build:
      context: ./frontend
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - dev

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - my-secrets.env
    volumes:
      - ./init_postgres_db.sql:/docker-entrypoint-initdb.d/init_postgres_db.sql
      - postgres_data:/var/lib/postgresql/data # Для сохранения данных между перезапусками
    networks:
      - dev

  backend:
    build:
      context: ./backend
    env_file:
      - my-secrets.env
    networks:
      - dev
    depends_on:
      - postgres

  telegram-bot:
    build:
      context: ./telegram-bot
    env_file:
      - my-secrets.env
    networks:
      - dev

volumes:
  postgres_data: