networks:
  dev:

services:
  nginx:
    ports:
      - "8097:8097"
    build:
      context: ./frontend
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    environment:
      REACT_APP_API_URL: /api
    networks:
      - dev

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sgEW35656fdf
      POSTGRES_DB: postgres
    volumes:
      - ./init_postgres_db.sql:/docker-entrypoint-initdb.d/init_postgres_db.sql
      - postgres_data:/var/lib/postgresql/data # Для сохранения данных между перезапусками
    networks:
      - dev

  backend:
    build:
      context: ./backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sgEW35656fdf
      POSTGRES_URL: jdbc:postgresql://postgres:5432/
    networks:
      - dev
    depends_on:
      - postgres

volumes:
  postgres_data: