name: Deploy to Local Server
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: akimenko
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run deploy script
        run: |
          echo "Deploying to local server..."
          ./deploy.sh
